### ISSUE TITLE
Using streaming with function calling is giving an error

### ISSUE THREAD

**Issue by debankurghosh2061** [OvidijusParsiunas/deep-chat#251] opened 2024-08-21 15:00 UTC
I've roughly got the following setup: 

1. I'm using the handler to connect to a custom AI API based on the Open AI API. 
2. The AI can stream the response back and perform function calling. 
3. The function calling is async. 

Issue experienced: 
1. When the AI asks me to perform a function call the chat gives the error: 

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/02d8cc36-695e-4d24-b065-f9077076b864">

I do **not** experience any error when AI does not ask to function call but instead streams the response back only.

Pseudo code: 
```javascript
chatElementRef.stream  = true;
chatElementRef.connect = {
  handler: async (body, signals) => {
    try {

      await custom.AI.createCompletion({
        model: "gpt",
        messages: messagesArr,
        temperature: 1,
        tools: tools,
        tool_choice: "auto",
        stream: true,
      }).stream(async function onChunk(chunk) {
        signals.onOpen();

        //Need to do a function call
        if (content.choices[0].delta.tool_calls) {
          let functionCallData = await customAsyncfunction();
          //Insert function call data to messages Array
          let response = await custom.AI.createCompletion({
            model: "gpt",
            messages: messagesArr,
            tools: tools,
            tool_choice: "auto",
            stream: true,
          }).stream(function onChunk(secondChunk) {
            if (secondChunk.choices[0].delta.content) {
              signals.onResponse({
                text: secondChunk.choices[0].delta.content,
              });
            }
          });
        }

        if (delta.content) {
          // no function calling needed
          signals.onResponse({ text: delta.content });
        }
      });
    } catch (e) {
      signals.onResponse({ error: error.message });
    }
  },
};
```

Any ideas on why this is happening? It seems to me that the chat doesn't want to wait for my async function call and throws that error. 

I am using version 2.0.1. 
Docs used: https://deepchat.dev/docs/connect/#Handler

**Comment by OvidijusParsiunas** [comment] 2024-08-21 16:25
Hi @debankurghosh2061.
Because it is difficult for me to reproduce the error on my end, I can't really pinpoint the exact problem, however I can point you to certain things that look a little out of place:
- The chaining of `custom.AI.createCompletion` and `.stream` seems strange. I think there could be a problem with `await` not waiting for the `stream` to finish.
- Also I am not seeing that you are using `signals.onClose()`, usually if you trigger `signals.onClose()` before any content has been returned it would throw the error that you have displayed. Did you remove it from your example? If you did, then the problem is that `signals.onClose()` is called before `signals.onResponse` is called. However, if you are not using `signals.onClose()`, please note that it is important to call it _after_ all `signals.onResponse` have finished calling.

Alternatively I would advise you to start removing some of your code to make it easier to identify the cause of the problem.

Let me know if this helps.
Thanks!

**Comment by debankurghosh2061** [comment] 2024-08-21 17:08
Hi @OvidijusParsiunas 

Thanks for your prompt response. It turns out you are right about the signals.onClose(), when I removed it this issue went away. 

I will restructure the code to close the signal properly. 

Awesome library btw, I was searching for a library that can handle custom AI apis with streaming markdown.

**Comment by OvidijusParsiunas** [comment] 2024-08-21 17:13
Good to hear. To note - this chat is great for non AI APIs as well and I am working on a clone of this project that has the [`directConnection`](https://deepchat.dev/docs/directConnection/) properties stripped out to make it more lean - called [Active Chat](https://github.com/OvidijusParsiunas/active-chat).

If your problem gets resolved, please close this issue. Thankyou!

**Closed** 2024-08-22 08:31 UTC
Labels: advice
