### ISSUE TITLE
Asynchronous responseInterceptor Interfering with Streaming Data Transmission May Cause Rendering Abnormalities

### ISSUE THREAD

**Issue by buzhou9** [OvidijusParsiunas/deep-chat#153] opened 2024-03-25 09:11 UTC
If a 'responseInterceptor' is provided as an asynchronous function and the server streams data in segments, if the execution time of the 'responseInterceptor' exceeds the interval between each segment of the streaming data process, due to the event loop execution mechanism of JavaScript, it can result in abnormal message rendering.

### Reproduction method
Modify the parameters for streaming data examples in this file
```js
// file url deep-chat/example-servers/nextjs/pages/index.tsx
<DeepChat
  style={{borderRadius: '10px'}}
  introMessage={{text: 'Send a streamed chat message to an example server.'}}
  request={{url: '/api/custom/chat-stream'}}
  stream={true}
  responseInterceptor={async (response: any) => {
    console.log(response);
    await new Promise(resolve => setTimeout(() => resolve(true), 500))
    console.log('return', response)
    return response;
  }}
/>
```

The complete content of this message is "This is a response from a NextJS server. Thank you for your message!"

![demo](https://github.com/OvidijusParsiunas/deep-chat/assets/26274418/1b82ba42-2ceb-4239-89fe-9f2be4a8559b)

**Comment by buzhou9** [comment] 2024-03-25 09:16
![Uploading 20240325-171525.gif…]()

**Comment by OvidijusParsiunas** [comment] 2024-03-30 16:15
Hi @buzhou9. My apologies for the late response.

What you are seeing is expected behaviour. The [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor) provides an _async_ modifier to allow developers to perform other asynchronous operations before returning the result. Whilst this works perfectly for normal requests, if developers intentionally delay some results - the message bubble will undoubtably also be populated with a delayed output.

The behaviour you expect is not easy to implement and would need an overhaul of the stream functionality. However given that the _unwanted_ behaviour is caused by the developer code, they should be the ones that should make sure the events are being returned in the order that they expect.

Because the [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor) functionality operates the way it needs to, I will be closing this issue. However, if you need any further advice, feel free to comment below.

**Closed by OvidijusParsiunas** 2024-03-30 16:15 UTC

**Comment by buzhou9** [comment] 2024-04-01 02:07
Thank you, I encountered this issue because the data returned from each stream has a special formatted string that needs to be parsed through an asynchronous function to render correctly. Of course, I have now resolved this issue by transferring the logic of this code to the server's code before streaming back.
