### ISSUE TITLE
Want a better example of learning combined with server

### ISSUE THREAD

**Issue by 1738970143** [OvidijusParsiunas/deep-chat#63] opened 2023-12-05 19:38 UTC
Sorry to bother you I‘m a student learning js and very interesting about this program.Even though i try my best to run it for almost 10hours i failed. Can you give me an example of the simplest html + js , i watched a day of video documentation and sandbox code， can you give me a full example to run  ?

I tried the following code to connect to the python sample server, but after modifying it many times it just gives me the following error：

    <deep-chat request='{ "url":"http://localhost:8080/openai-chat"}'
    id="chatBox"
    style="border-radius: 10px; position: fixed; bottom: 40px; right: 20px; z-index: 1;display: none"
  ></deep-chat>

127.0.0.1 - - [06/Dec/2023 03:21:24] "OPTIONS /openai-chat HTTP/1.1" 200 -
<Request 'http://localhost:8080/openai-chat' [POST]>
can only concatenate str (not "NoneType") to str
127.0.0.1 - - [06/Dec/2023 03:21:24] "POST /openai-chat HTTP/1.1" 500 -

Can you help me with some particularly detailed examples of instruction? Your website instructions and examples are just too simple and abstract.

**Comment by OvidijusParsiunas** [comment] 2023-12-05 21:06
Hi. Your code looks correct. This repo has full [server examples](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers) for the backend and full [live examples](https://deepchat.dev/examples/frameworks) for the frontend so there shouldn't be any more example code needed.

Could you perhaps share a bit more about your implementation. I know you are trying to run the [python/flask](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/python/flask) backend. Were you able to run it successfully?

**Comment by OvidijusParsiunas** [comment] 2023-12-05 21:25
Actually I just noticed there is a problem in your example - you are connecting to the `http://localhost:8080/openai-chat` endpoint. When using the OpenAI endpoints, they require a `model` value to be passed in via the `additionalBodyProps` object.
I would recommend checking out the [UI](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/ui) project which has been designed to connect to all of the example backends (as mentioned in this [section](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/python/flask#calling-ui-component)). It shows the required configuration needed for each endpoint.

So in your example, you should change your code to:

```
<deep-chat
  request='{"url":"http://localhost:8080/openai-chat", "additionalBodyProps": {"model": "gpt-3.5-turbo"}}'
  id="chatBox"
  style="border-radius: 10px; position: fixed; bottom: 40px; right: 20px; z-index: 1; display: none"
></deep-chat>
```
I noticed you are also using `display: none` which I am not sure if is intentional.

Finally, in the Python project, make sure to create a `.env` file which is similar to `.env.example` file and populate the `OPENAI_API_KEY=key-here` with your OpenAI key value.

Make sure to follow the Python [Local Setup](https://github.com/OvidijusParsiunas/deep-chat/blob/main/example-servers/python/flask/README.md#computer-local-setup) instructions carefully.

Let me know if you need any more assistance.

**Comment by 1738970143** [comment] 2023-12-06 05:14
I was very pleasantly surprised to receive such a quick reply from you and thank you now.
I would really like to run your ui sample project, when I open it I only see the following command which is exactly the same as the other server example
<img width="1071" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/90264219/41dddb9a-2078-4a12-b49f-5c2ad871e8b3">
but when I run this in the /Users/linyong/vscode/deep-chat/example-servers/ui folder it like this :
<img width="1264" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/90264219/adee2275-cc98-4a77-912e-2228d3102db1">
I've tried in other paths with no success
So could you please give a little bit of detailed steps and screenshots of successfully running the example on your page? So that newbies like me can study your code and learn!


Also, I tried to modify the code like you said. I just wrote this bit in the html
<img width="939" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/90264219/74a3fe0c-73be-47dd-9162-30683afaa5c7">
For the python example server I didn't make any changes and just printed the request.
@app.route("/openai-chat", methods=["POST"])
def openai_chat():
    print(request)
    body = request.json
    return open_ai.chat(body)

Then every time I run the front end to send a message, I get this reply behind it, without even going inside the openai.py file.


In any case I thank you very much for your reply and wish you the best of luck in your endeavours, I will do my best to learn all the advice you give and your code!

**Comment by 1738970143** [comment] 2023-12-06 08:45
I think  the direct connection to openai is most convient , but I am in china and can't approch to openai directly ,so is there a change url method for directConnection='{"openAI":?

**Comment by OvidijusParsiunas** [comment] 2023-12-06 17:27
This is very strange, the fact that you can't run the React UI example indicates that there is a potential problem with your `node`/`npm` setup. However, if you are able to use the chat in your own UI then don't worry about it I guess.

I am trying to think what else could be causing the problem. How, are you hosting your UI? Is it just a `.html` file?

Can you run  the `url` to `http://localhost:8080/chat` to see if it works. If it does, then there is a problem in the Python server when connecting to OpenAI, if it does not work then the problem is in your setup.

The [directConnection OpenAI](https://deepchat.dev/docs/directConnection/openAI#openAI) property is specifically configured to handle requests and responses that come from OpenAI which do not adhere to the standard [MessageContent](https://deepchat.dev/docs/messages/#MessageContent) format, therefore changing the URL will not yield any benefit.

It is important to note that if your computer cannot connect to OpenAI from the browser, the Python server will also not work as API calls are based on your location/IP.

**Comment by 1738970143** [comment] 2023-12-07 08:42
thank you for your response . I'll try to find a new computer and try to run the ui demo. Could I just copy the ui file and npm
 install / npm run start in that file ? 
I host  my web with http-server .
what's more , how can i learn more about the parameters of the <deep-chat>? Can I get other demo codes from you or more vedios?
Hoping you have a good day

**Comment by OvidijusParsiunas** [comment] 2023-12-11 20:01
Sorry for the late reply as I didn't see the notification. Yes, you should be able to clone the [UI project](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/ui) and follow the setup in the [README.md](https://github.com/OvidijusParsiunas/deep-chat/blob/main/example-servers/ui/README.md) file. You will ofcourse need to also run any of our example servers.

Alternatively I recommend trying out the [NextJs](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/nextjs) example which has the front-end and back-end all in the same project, which might be more convenient.

The current videos on Youtube are enough for people to get started, however I will of-course be creating more in the near future as more updates are added to Deep Chat.

**Comment by OvidijusParsiunas** [comment] 2023-12-13 19:19
I will be closing this issue now, however if you have any other issues, please feel free to raise a new one.
Thankyou!

**Closed by OvidijusParsiunas** 2023-12-13 19:19 UTC
Labels: advice
