### ISSUE TITLE
Auto submit of text after audio input

### ISSUE THREAD

**Issue by AravindKaay** [OvidijusParsiunas/deep-chat#133] opened 2024-02-21 05:45 UTC
Feature suggestion: I wish there were a prop that enables auto-submit of text based on audio input. It won't be very pleasant for the user to say a word to submit every time. I mean it should auto-submit after some seconds of inactivity from the user

**Comment by bharathmorg** [comment] 2024-02-21 13:35
I am also facing this issue, could you please provide an solution for this issue or is there any alternate method

**Comment by OvidijusParsiunas** [comment] 2024-02-21 15:54
Hi, submitting a message on a _pause_ is difficult to standardise due to dynamic human speech intensions. For example, if the user speaks and later decides to think for a moment, automatically sending a message to the server would be the last thing that they would want. Hence, this is a relatively _volatile_ problem depending on your chat audience.
I will try to see if I can implement something to help you out, but it may take some time depending on what needs to be changed. I'll let you know more details later tonight when I get some free time. Thanks!

**Comment by OvidijusParsiunas** [comment] 2024-02-22 02:13
Hi, I did some experimentation and was able to create automated submit on silence functionality. I will create an API for this and deploy it in dev tomorrow so you can test it out.
One small issue I ran into was that whilst this works - the functionality to keep the recording going after submission is quite difficult. It does work well for the _submit_ command because the [Speech To Element]() library that is used has been preconfigured to automatically restart after after a particular phrase has been spoken, but I can't do that on silence.

Hence, right now - stopping the recording after submit has happened works perfectly, and if you want to keep the recording going after submit - there is a 300 millisecond interim where the microphone is not available and then the recording automatically restarts again. Let me know if this fits your use-case (or if the first option is enough for you).

I also noticed a bug where upon recording the speech - the submit button is not clickable, I will also be fixing that. Thanks!

**Comment by AravindKaay** [comment] 2024-02-22 03:01
I want the microphone to be on continuously after submission and that 300 milliseconds time gap is not a big deal for me .

**Comment by marioseixas** [comment] 2024-02-22 11:34
> Hi, I did some experimentation and was able to create automated submit on silence functionality. I will create an API for this and deploy it in dev tomorrow so you can test it out.
> 
> One small issue I ran into was that whilst this works - the functionality to keep the recording going after submission is quite difficult. It does work well for the _submit_ command because the Speech To Element library that is used has been preconfigured to automatically restart after after a particular phrase has been spoken, but I can't do that on silence.
> 
> Hence, right now - stopping the recording after submit has happened works perfectly, and if you want to keep the recording going after submit - there is a 300 millisecond interim where the microphone is not available and then the recording automatically restarts again. Let me know if this fits your use-case (or if the first option is enough for you).
> 
> I also noticed a bug where upon recording the speech - the submit button is not clickable, I will also be fixing that. Thanks!

very nice, gonna use this also too, thanks!

the 300 ms is not a big deal for me either

**Comment by OvidijusParsiunas** [comment] 2024-02-22 16:57
Hi, I have made the changes and updated our `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.137` to have all the latest functionality.
The [`speechToText`](https://deepchat.dev/docs/speech#speechToText) setting has a new property called `submitAfterSilence` which accepts a boolean true or a json object. Here is its type:

```submitAfterSilence?: true | {ms?: number; stop?: boolean};```

The `ms` property is the milliseconds before the automated submit takes place. `stop` is used to toggle whether the speech to text recording will stop after the submit.
If the value is _true_ or either of the two properties are not defined, the following are the default values:

```{ms: 2000, stop: false}```

Here are example usages of the new `submitAfterSilence` property (Vanilla JavaScript):

```
speechToText = {submitAfterSilence: true}

speechToText = {submitAfterSilence: {}}

speechToText = {submitAfterSilence: {ms: 3000}}

speechToText = {submitAfterSilence: {stop: false}}

speechToText = {submitAfterSilence: {ms: 3000, stop: false}}
```

To note, if you are using the default [webSpeechAPI](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) for the speech to text service, it automatically stops after around 5-7 seconds of silence (by browser), therefore if you are defining a custom `ms` value - please be aware of that.

Final thing to mention. The `dev` packages behave the same way as the original ones - except their names are different. The next release for Deep Chat is going to be a big one as we are migrating a lot of its logic to another web component called [active chat](https://github.com/OvidijusParsiunas/active-chat) and with that we are changing quite a few property names, such as changing the [`request`](https://deepchat.dev/docs/connect#request) property to `connect` and [`initialMessages`](https://deepchat.dev/docs/messages/#initialMessages) to `history`. The old properties will still keep working as usual except you will see warnings in the console for their deprecation. Most importantly, because this is going to be a very big release - it is likely that it will take place some time next month, so all the `submitAfterSilence` will have to remain in the `dev` packages until it happens. Hopefully this is ok for you folks.

Let me know if you have any questions or issues.
Thanks!

**Comment by OvidijusParsiunas** [comment] 2024-02-23 17:16
The bug where the submit button is not enabled after speech transcription takes place has now been fixed in `deep-chat-dev` and `deep-chat-react-dev` version `9.0.138`.

**Comment by OvidijusParsiunas** [comment] 2024-02-23 17:52
Hey, I'm not 100% sure what you mean.

Do you want to access your website's DOM when you receive a chat response? If so, you can simple listen to the [onNewMessage](https://deepchat.dev/docs/events#onNewMessage) event and traverse the DOM when it is triggered. I'm confused as to how this is linked to the auto-submit speech to text functionality.

**Comment by AravindKaay** [comment] 2024-02-23 18:09
Thanks for your response. My query is not related to audio input now kindly bear with me asking about a different issue in this ticket. The onNewMessage Event is not useful in my case I can only add a script tag inside my code which is a cdn and with that cdn I need to access the dom of the host website and perform a task. I cannot declare the deepchat component in my code.

**Comment by OvidijusParsiunas** [comment] 2024-02-23 19:27
Probably would be better. You can still keep this issue open until the requested feature has been released in the main package :)

**Comment by AravindKaay** [comment] 2024-03-05 10:15
I found a bug like the microphone button icon color is changed to default after a response from service but after that also I can speak and my voice is transcribed to text. I need to persist the icon color even after response from server

**Comment by OvidijusParsiunas** [comment] 2024-03-05 21:15
Hey @AravindKaay. Thankyou for reporting the bug.
I had another look into the silence functionality and have updated the overall Speech To Text API. The [speechToText](https://deepchat.dev/docs/speech#speechToText) interface now looks like this:
```
...
stopAfterSubmit?: false;
submitAfterSilence?: true | number;
```
The `stopAfterSubmit` property is used to toggle whether the recording stops after the message has been submitted.
The `submitAfterSilence` property is used to toggle the automatic submit after silence functionality. You can either set it to _true_ or use a number to represent the number of milliseconds of silence required before submit.

The defaults for these values are:
```
...
stopAfterSubmit: true,
submitAfterSilence: false
```
If `submitAfterSilence` is set to _true_, then the default number of milliseconds is _2000_ (2s).

Example usage (Vanilla JavaScript):
```
speechToText = {submitAfterSilence: true}

speechToText = {submitAfterSilence: 3000}

speechToText = {stopAfterSubmit: false}

speechToText = {submitAfterSilence: true, stopAfterSubmit: false}

speechToText = {submitAfterSilence: 3000, stopAfterSubmit: false}
```

This has been published in `deep-chat-dev` and `deep-chat-react-dev` versions `9.0.142`. Let me know if this works for you and fixes your problem. If the issue is still occurring could you share the Deep Chat configuration you are using.

Thankyou!

**Comment by AravindKaay** [comment] 2024-04-09 06:12
I have used stopafterSubmit to restrict the microphone to listen to what the system is speaking but I have to start it again for the next conversation. Could you help me in solving this issue?

**Comment by OvidijusParsiunas** [comment] 2024-07-16 11:41
Hi @AravindKaay. Could you give me the steps and code to reproduce the issue please. Thankyou!

**Comment by OvidijusParsiunas** [comment] 2024-07-16 11:45
The new `stopAfterSubmit`, `submitAfterSilence` and other properties are now available in the [`speechToText`](https://deepchat.dev/docs/speech#speechToText) interface in Deep Chat version `2.0.0`.

If there are any problems relating to to this issue feel free to comment below, for everything else please create a new issue.
Thankyou!

**Closed by OvidijusParsiunas** 2024-07-16 11:45 UTC
Labels: enhancement

**Comment by CKGrafico** [comment] 2024-08-19 19:23
The feature is really nice @OvidijusParsiunas  thank you, it is working well on my computer but is definitely not sending after silence on my phone (iphone 11 using safari) any idea how to debug it?
