### ISSUE TITLE
HuggingFace - time out error

### ISSUE THREAD

**Issue by shivrajjadhav733** [OvidijusParsiunas/deep-chat#203] opened 2024-05-21 15:24 UTC
Hi,

I went to example-servers folder.
I used Java sample for server and UI example. 
I have added hugging face api key to application.properties
Besides that there is no change at all to any of the codebase.

When I try to interact on UI, I get error either as operation timed out or network unreachable.
Is it something related to proxy? If yes, where to set proxy. Can you share sample code?

![4D8F44A7-268A-44B6-A72A-F033319D43EB](https://github.com/OvidijusParsiunas/deep-chat/assets/35407279/420c45c1-0ce8-45b3-831e-be699312df9e)

![0282CA70-506E-46CF-9662-587EA1D4DA83](https://github.com/OvidijusParsiunas/deep-chat/assets/35407279/39029f37-5fa7-4fc3-a1de-c75e2537f729)
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/35407279/9a53d924-221b-4edf-8e4d-3ee5e6c942ac)

**Comment by OvidijusParsiunas** [comment] 2024-05-22 14:22
Hi @shivrajjadhav733. There is no proxy and things should work right out of the box.
Having said that, there are two types of errors that you can expect from Hugging Face:
- The first one is a common one that is thrown the first time you call a mode. If a model has not been called in a long time - Hugging Face will return an error stating that you will need to wait for it to load. Because our [example-servers](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers) are just basic starter kits and this error is thrown for certain models we do not provide a code example to fix this and devs should implement their own way that suits their use-cases. In addition to this, once the model has loaded up the subsequent requests should work fine:
```{"error":"Model facebook/blenderbot-400M-distill is currently loading","estimated_time":29.19023895263672}```
- If you are using the [`Conversation`](https://deepchat.dev/docs/directConnection/HuggingFace#Conversation) example, you will get the error below. The reason for this is because their [documentation](https://huggingface.co/docs/api-inference/detailed_parameters?code=js#conversational-task) does not reflect the actual implementation that is required to call their conversation API, hence the error below is returned. I have also raised the following [post](https://discord.com/channels/879548962464493619/1222016268945588230) in their Discord for some help but have not gotten anything useful back. I will continue to investigate this:
```{"error":" `args[0]`: {'text': 'Hi', 'past_user_inputs': [], 'generated_responses': []} have the wrong format. The should be either of type `str` or type `list`","warnings":["There was an inference error:  `args[0]`: {'text': 'Hi', 'past_user_inputs': [], 'generated_responses': []} have the wrong format. The should be either of type `str` or type `list`"]}```

Having said all of this, the error in your screen appears to be related with something potentially in your network. It could be because of the region you are in or a proxy/vpn that you may have. I would recommend trying to call their [APIs](https://huggingface.co/docs/api-inference/detailed_parameters#detailed-parameters) via cURL/[Postman](https://www.postman.com/) instead and seeing if you get the same error. I would then try to check any issues with your network.

Apologies for not being able to help much more as I cannot reproduce the issue. Sorry.

**Comment by OvidijusParsiunas** [comment] 2024-07-16 12:50
I will close this issue since there has been no further communication on it.

**Closed by OvidijusParsiunas** 2024-07-16 12:50 UTC
Labels: advice
