### ISSUE TITLE
Unable to create placeholder message in index.tsx - NextJs

### ISSUE THREAD

**Issue by root-runner** [OvidijusParsiunas/deep-chat#88] opened 2024-01-04 11:50 UTC
I'm not the best proompt engineer out there so I'm having a little trouble adding a placeholder message to my chatbot. I've added the following code to the deepchat tag, but I keep getting the "expression expected error" when running locally.

`<div
                     style={{
                        width: "200px",
                        backgroundColor: "#f3f3f3",
                        borderRadius: "10px",
                        padding: "12px",
                        paddingBottom: "15px",
                        display: "none",
                     }}
                  >
                     <div>
                        <div style={{textAlign: "center", marginBottom: "8px", fontSize: "16px"}}>
                           <b>Intro panel</b>
                        </div>
                     <div style={{fontSize: "15px", lineHeight: "20px"}}>
                        Insert a description to help your users understand how to use the component.
                     </div>
                  </div>`

The error is as follows:

<img width="978" alt="Screenshot 2024-01-04 at 22 50 26" src="https://github.com/OvidijusParsiunas/deep-chat/assets/75192659/c5272beb-fbb4-479b-90fa-c06d064c4422">

I've tried formatting several different ways to no avail. Any help would be appreciated!

**Comment by OvidijusParsiunas** [comment] 2024-01-04 16:49
Hi @root-runner.
If you are attempting to insert an [intro panel](https://deepchat.dev/docs/introPanel) into the chat, it appears you are missing a closing `</div>` tag in your syntax. Here is the full working code:

```
<DeepChat demo={true}>
  <div
    style={{
      width: '200px',
      backgroundColor: '#f3f3f3',
      borderRadius: '10px',
      padding: '12px',
      paddingBottom: '15px',
      display: 'none',
    }}
  >
    <div>
      <div style={{textAlign: 'center', marginBottom: '8px', fontSize: '16px'}}>
        <b>Intro panel</b>
      </div>
      <div style={{fontSize: '15px', lineHeight: '20px'}}>
        Insert a description to help your users understand how to use the component.
      </div>
    </div>
  </div>
</DeepChat>
```

Let me know if you need any further assistance. Thanks!

**Comment by root-runner** [comment] 2024-01-05 12:09
Hey mate, thanks for the speedy reply. Should also mention that this repo is an amazing creation, so well done.

Oops for overlooking the closing div tag... I fixed that according to what you wrote, but unfortunately to no avail. If I add the '>' to the DeepChat element:
<img width="118" alt="Screenshot 2024-01-05 at 23 04 07" src="https://github.com/OvidijusParsiunas/deep-chat/assets/75192659/aaf51dbd-3c4b-4480-8d3a-b01fef2356fb">
then I get a runtime error:
<img width="987" alt="Screenshot 2024-01-05 at 23 04 40" src="https://github.com/OvidijusParsiunas/deep-chat/assets/75192659/d3efb398-6b7d-426b-b0c3-a82780caa8a5">

If I leave it open:
<img width="114" alt="Screenshot 2024-01-05 at 23 05 09" src="https://github.com/OvidijusParsiunas/deep-chat/assets/75192659/27bc8eae-1312-40f6-8426-d7ca1df6aa51">
Then everything works except for the intro panel. I get an error as follows:
<img width="742" alt="Screenshot 2024-01-05 at 23 07 55" src="https://github.com/OvidijusParsiunas/deep-chat/assets/75192659/ebbd568b-9e48-454e-bce4-4f18fff12d37">

Any thoughts? I don't have much experience with react or typescript. Everything has been recently updated and I a using typescript with my project.

**Comment by OvidijusParsiunas** [comment] 2024-01-05 14:58
That is quite strange. I have tested the code on the [example React project](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/ui) and the [live React project](https://codesandbox.io/p/sandbox/deep-chat-react-vwh8ls?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb8qu8500073b6hta5verz5%2522%252C%2522sizes%2522%253A%255B83.77331420373028%252C16.22668579626972%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb8qu8400033b6h262iud1y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb8qu8500043b6h2ntw7fat%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb8qu8500063b6hh21vm3z6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb8qu8400033b6h262iud1y%2522%253A%257B%2522id%2522%253A%2522clpb8qu8400033b6h262iud1y%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpb8qu8500063b6hh21vm3z6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb8qu8500053b6h8jrptawv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpb8qu8500063b6hh21vm3z6%2522%252C%2522activeTabId%2522%253A%2522clpb8qu8500053b6h8jrptawv%2522%257D%252C%2522clpb8qu8500043b6h2ntw7fat%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpb8qu8500043b6h2ntw7fat%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and it seems to work fine for me.

It might be something caused by the setup in your application.
It is also interesting that you are inserting your code in an `index.tsx` file, usually the code is inserted in the `app.tsx`. It should not matter, but worth trying out.

Here is a [live example](https://codesandbox.io/p/sandbox/deep-chat-react-forked-y6dp4w?file=%2Fsrc%2FApp.tsx%3A9%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb8qu8500073b6hta5verz5%2522%252C%2522sizes%2522%253A%255B83.77331420373028%252C16.22668579626972%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb8qu8400033b6h262iud1y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb8qu8500043b6h2ntw7fat%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb8qu8500063b6hh21vm3z6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb8qu8400033b6h262iud1y%2522%253A%257B%2522id%2522%253A%2522clpb8qu8400033b6h262iud1y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr0ra75a00673b6hcl2p90to%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr0ra75a00673b6hcl2p90to%2522%257D%252C%2522clpb8qu8500063b6hh21vm3z6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb8qu8500053b6h8jrptawv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpb8qu8500063b6hh21vm3z6%2522%252C%2522activeTabId%2522%253A%2522clpb8qu8500053b6h8jrptawv%2522%257D%252C%2522clpb8qu8500043b6h2ntw7fat%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpb8qu8500043b6h2ntw7fat%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of the code used in my example. You can try to replicate it as close as possible to your React application to see where the cause is.

**Comment by root-runner** [comment] 2024-01-10 10:56
Hey @OvidijusParsiunas,

I think I managed to get it working. Firstly, unsure why the code is in the `index.tsx` file - I am using next.js and this is the way it was setup when I initiated the app.

The code below is what I hade previously:

```
               <DeepChat
                  style={{
                     borderRadius: "10px",
                     border: "1px solid #bcbcbc",
                     backgroundColor: "#292929",
                     width: "100%",
                     height: "70vh",
                     fontSize: "1rem",
                  }}
                  messageStyles={{
                     default: {
                        ai: {
                           bubble: {backgroundColor: "#545454", color: "white"},
                        },
                     },
                     loading: {
                        bubble: {backgroundColor: "#545454", color: "white"},
                     },
                     error: {
                        bubble: {
                           backgroundColor: "#f98e00",
                           color: "white",
                           fontSize: "1rem",
                        },
                     },
                  }}
                  textInput={{
                     styles: {
                        container: {
                           width: "100%",
                           margin: "0",
                           borderRadius: "0",
                           borderTop: "1px solid #bcbcbc",
                           boxShadow: "unset",
                           backgroundColor: "#666666",
                           color: "#e8e8e8",
                        },
                        text: {
                           padding: "0.8rem 0.8rem 0.8rem 1.4rem",
                        },
                     },
                     placeholder: {
                        text: "Ask a question...",
                        style: {color: "#bcbcbc"},
                     },
                  }}
                  submitButtonStyles={{
                     submit: {
                        container: {
                           default: {
                              transform: "scale(1.2)",
                              margin: "-3px 20px",
                           },
                        },
                     },
                  }}
                  directConnection={{
                     openAI: {
                        key: "hidden",
                        assistant: {
                           assistant_id: "hidden",
                        },
                     },
                  }}
                  mixedFiles={false}
               />

```

And I managed to fix it by adjusting such a small part of the code to get this:
```
               <DeepChat
                  style={{
                     borderRadius: "10px",
                     border: "1px solid #bcbcbc",
                     backgroundColor: "#292929",
                     width: "100%",
                     height: "70vh",
                     fontSize: "1rem",
                  }}
                  messageStyles={{
                     default: {
                        ai: {
                           bubble: {backgroundColor: "#545454", color: "white"},
                        },
                     },
                     loading: {
                        bubble: {backgroundColor: "#545454", color: "white"},
                     },
                     error: {
                        bubble: {
                           backgroundColor: "#f98e00",
                           color: "white",
                           fontSize: "1rem",
                        },
                     },
                  }}
                  textInput={{
                     styles: {
                        container: {
                           width: "100%",
                           margin: "0",
                           borderRadius: "0",
                           borderTop: "1px solid #bcbcbc",
                           boxShadow: "unset",
                           backgroundColor: "#666666",
                           color: "#e8e8e8",
                        },
                        text: {
                           padding: "0.8rem 0.8rem 0.8rem 1.4rem",
                        },
                     },
                     placeholder: {
                        text: "Ask a question...",
                        style: {color: "#bcbcbc"},
                     },
                  }}
                  submitButtonStyles={{
                     submit: {
                        container: {
                           default: {
                              transform: "scale(1.2)",
                              margin: "-3px 20px",
                           },
                        },
                     },
                  }}
                  directConnection={{
                     openAI: {
                        key: "hidden",
                        assistant: {
                           assistant_id: "hidden",
                        },
                     },
                  }}
                  mixedFiles={false}
               >
                  <div
                     style={{
                        width: "200px",
                        backgroundColor: "#f3f3f3",
                        borderRadius: "10px",
                        padding: "12px",
                        paddingBottom: "15px",
                        display: "none",
                     }}
                  >
                     <div>
                        <div
                           style={{
                              textAlign: "center",
                              marginBottom: "8px",
                              fontSize: "16px",
                           }}
                        >
                           <b>Intro panel</b>
                        </div>
                        <div style={{fontSize: "15px", lineHeight: "20px"}}>
                           Insert a description to help your users understand
                           how to use the component.
                        </div>
                     </div>
                  </div>
               </DeepChat>
```

Basically - I had included the place holder as a part of the DeepChat tag:
```
<DeepChat 
     {styles-code}
     {placeholder-code} 
/>
``` 

When all I needed to do was include it BETWEEN an opening and closing tag, and not with the styles code:
```
<DeepChat
     {styles-code}
/>
     {placeholder-code}
</DeepChat>
```

I've attached the full index.tsx file I used for this react project in case you're curious.

[index.tsx.zip](https://github.com/OvidijusParsiunas/deep-chat/files/13886638/index.tsx.zip)

**Comment by OvidijusParsiunas** [comment] 2024-01-10 18:39
Glad you got the issue resolved @root-runner!

I will close this issue. If you have any further questions, please raise a new issue. Thankyou!

**Closed by OvidijusParsiunas** 2024-01-10 18:39 UTC
Labels: advice
