### ISSUE TITLE
websocket connection getting called many times at start

### ISSUE THREAD

**Issue by nishit-g** [OvidijusParsiunas/deep-chat#52] opened 2023-11-24 19:45 UTC
So, i am modifying the websocket sample template provided ,

Now the websocket handler or is trying to call connection many times sometimes , causing issues and the sometimes not rendering the messages as well. 

Why is the handler being called many times ? How can i stop that thing ? 

[Sandbox](https://codesandbox.io/p/sandbox/deep-chat-react-forked-mxyt6g?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb3dxu200072a67ai4fra3l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb3dxu200032a671eooyd8s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb3dxu200042a67mf693zmq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb3dxu200062a67mnjyr4pp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B63.64246024142556%252C36.35753975857444%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb3dxu200032a671eooyd8s%2522%253A%257B%2522id%2522%253A%2522clpb3dxu200032a671eooyd8s%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpb3dxu200062a67mnjyr4pp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb3dxu200052a67ywipi7p8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpb3dxu200062a67mnjyr4pp%2522%252C%2522activeTabId%2522%253A%2522clpb3dxu200052a67ywipi7p8%2522%257D%252C%2522clpb3dxu200042a67mf693zmq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpb3dxu200042a67mf693zmq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by OvidijusParsiunas** [comment] 2023-11-24 21:52
Hi @nishit-g.
Based on your example everything appears to be in order.
The reason why the _connection_ is being called multiple times (twice) is because in React dev mode the dom is rendered twice. It is a pretty standard convention in React and should not cause any problems. However if there are more than two attempts let me know as that is not the expected behaviour.

The reason why your messages are not rendering correctly is _likely_ because new ones are being generated whilst older ones are still being streamed. Asynchronous message stream simulation in websockets is not supported in Deep Chat version `1.4.3`. Luckily this is good timing as version `1.4.4` which is going to be released this Sunday will support this. You can get early access to it by using the `deep-chat-dev` and `deep-chat-react-dev` packages versioned `9.0.66`. So you can either use them or not use the `stream={{ simulation: 150 }}` property until the new version is released Sunday.

Let me know if you are still having any problems.
Thanks!

**Comment by OvidijusParsiunas** [comment] 2023-11-25 20:48
Hi. The functionality discussed above has now been released in Deep Chat version `1.4.4`. Please read the [release notes](https://github.com/OvidijusParsiunas/deep-chat/releases/tag/1.4.4) for more information.

To note, `simulation` functionality has been changed to populate by character rather than word. So the recommended default number value is _6_, but you can ofcourse change it to your preference.

I will be closing this issue, but if you experience problems relating to streaming feel free to comment below or raise a new issue for anything else. Thanks!

**Closed by OvidijusParsiunas** 2023-11-25 20:48 UTC
Labels: advice
