### ISSUE TITLE
How to get correct response from the api method?

### ISSUE THREAD

**Issue by guinanlin** [OvidijusParsiunas/deep-chat#22] opened 2023-10-26 08:44 UTC
I attempted dialogue integration using the following code. However, I examined the results, 
and the response received is not coming from the server. 
In theory, the server should return the following JSON:

``
{
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How can I assist you today as a policy consulting expert for corporate parks?"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 93,
    "completion_tokens": 17,
    "total_tokens": 110
  }
}
``

my deep-chat:

`<deep-chat
    id="chat-element"
    demo="true"
    style=" border-radius: 10px;
            height: calc(95vh - 5.5rem);;
            width: 600px;
            border: 1px solid rgb(202, 202, 202);
            font-family: Inter, sans-serif, Avenir, Helvetica, Arial;
            font-size: 1.2rem;
            background-color: white;
            position: relative;"
    :request='{
    "url": "https://xxx.chat/v1/chat/completions",
    "headers": {
        "Content-Type": "application/json",
        "Authorization": "Bearer LixxxtO7"
    }
    }'   
    :requestInterceptor="(request) => {
        // request.body = {prompt: request.body.messages[0].text};
        request.body = { app_code: 'pKxxxxjc5',
                         messages: [
                            {
                            role: 'user',
                            content: request.body.messages[0].text
                            },
                        ]
                        };
        return request;      
    }"

    :responseInterceptor="(response) => {
            // const responseText = // extract it from the response argument
            return {result: {text: response.detail}}
    }"  
>
</deep-chat>`

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/681a945d-5691-4425-b319-165640eda65f)

**Comment by OvidijusParsiunas** [comment] 2023-10-26 11:36
Hi @guinanlin, thankyou for raising an issue.
Based on the example response JSON from the server you have provided, the interceptor should be as follows:

Your JSON:
```
{
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How can I assist you today as a policy consulting expert for corporate parks?"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 93,
    "completion_tokens": 17,
    "total_tokens": 110
  }
}
```

[`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor) code (tailored for Vue):

```
:responseInterceptor="
      (response) => {
        return { text: response.choices[0].message.content };
      }"
```

**Comment by guinanlin** [comment] 2023-10-26 11:54
"It's still not working; I don't know how the result of this 'response' is generated. However, when I make a call using a tool similar to Postman, the call works fine.

I've even traced the breakpoints, and they enter the requestInterceptor and responseInterceptor as expected. The value of request.body is correct, but the result of the response is incorrect.

I'm using 'deep-chat': '^1.3.19'."

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/b3d4de7c-13f0-4dac-a4cc-b53804de6db1)

the correct result should be as following :
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/0545a19c-0abc-4ec3-9b48-21bccf5840f8)

following is my core code:
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/c42e2b72-509f-4959-9f93-07f131955702)

**Comment by OvidijusParsiunas** [comment] 2023-10-26 12:06
Ok, I understand the problem now. It appears Deep Chat is sending an incorrect request to your server. Let me experiment a little bit to see if I can identify the exact cause for this.

**Comment by OvidijusParsiunas** [comment] 2023-10-26 12:09
Can you try to remove the `Content-Type:  "application/json"` property from the request headers and tell me if anything changes.

**Comment by OvidijusParsiunas** [comment] 2023-10-26 12:20
I identified a bug in the component, let me try to fix it now.

**Comment by guinanlin** [comment] 2023-10-26 12:22
remove content-type:

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/6104821e-5f60-450c-a439-360668371df1)


> Can you try to remove the `Content-Type: "application/json"` property from the request headers and tell me if anything changes.

**Comment by guinanlin** [comment] 2023-10-26 12:27
I wirte a js function to get the reuslt:

```
    async getOpenAIResult(query) {
      // 检查 initialize 是否已经完成，如果未完成，等待它完成
      if (!this.frappe) {
        await this.initialize();
      }
    
      return new Promise((resolve, reject) => {
        const url = 'https://axxxxxcompletions';
        const headers = {
          'Content-Type': 'application/json', 
          'Authorization': "Bearer Link_xxxxxxx9uzD0tO7",
        };
    
        const requestBody = JSON.stringify(query);

        console.log("requestbody content:",requestBody);
    
        fetch(url, {
          method: 'POST',
          headers: headers,
          body: requestBody
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          resolve(data);
        })
        .catch(error => {
          reject(error);
        });
      });
    }
```

call in onMounted:

```
onMounted(()=>{
    const query = {
        "app_code": "pxxxxxjc5",
        "messages": [
            {
            "role": "user",
            "content": "Hello"
            },
        ]
    }
    frappeService.getOpenAIResult(query).then((data) => {        
        console.log('result:',data);
    });        
});
```

I will get the correct response:
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/6083b98f-e1d5-4aed-ab4d-cbd8bc7da865)

**Comment by OvidijusParsiunas** [comment] 2023-10-26 12:34
There was a bug introduced in the last release, I have updated the code in version `1.3.20`. Can you try it and see if it works for you? Thanks!

**Comment by OvidijusParsiunas** [comment] 2023-10-26 14:24
That is quite strange, I have tested the new version and it appears to be sending the messages correctly. Are you 100% sure that your are using the new version after doing `npm install`?

**Comment by OvidijusParsiunas** [comment] 2023-10-26 14:44
Can you try the following configuration and see if it works - you will need to replace the `your-api-key-here` with your bearer key:

```
<deep-chat
    :request="{
      url: 'https://api.openai.com/v1/chat/completions',
      headers: {
        Authorization: 'Bearer your-api-key-here',
      },
    }"
    :requestInterceptor="
      (request) => {
        request.body = {
          messages: [{ role: 'user', content: request.body.messages[0].text }],
          model: 'gpt-3.5-turbo',
        };
        return request;
      }
    "
    :responseInterceptor="
      (response) => {
        return { text: response.choices[0].message.content };
      }
    "
  />
```

Here is a link to a live [CodeSandbox](https://codesandbox.io/s/deep-chat-vue3-forked-d377h5?file=/src/App.vue:13-545)

If this configuration works in your app and you get successful response, but the configuration to connect to your service is still not working then there is still a problem with something else.
If this configuration is not working in your app, then you are not using the latest version (`1.3.20`) of Deep Chat.

Let me know how it goes for you and I will continue to help!

**Comment by guinanlin** [comment] 2023-10-26 15:35
via your code to test OpenAI interface, In my env will ocurrs the same errors:
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/afd72e49-8959-47ec-a694-ac399d0b5ab3)

the response error:
{
    "message": "you must provide a model parameter",
    "type": "invalid_request_error",
    "param": null,
    "code": null
}

but the same openai key run on the codesanbox works well.
My god, it's so strange.

**Comment by OvidijusParsiunas** [comment] 2023-10-26 15:38
If the exact same code from the sandbox doesn't work in your local application then I would assume your app is running the `1.3.19` version instead.
Can you try delete the `package-lock.json` file and `node_modules` folder, and do `npm install` again to see if it works.

**Comment by OvidijusParsiunas** [comment] 2023-10-26 15:44
Also, if you are able to inspect the Deep Chat code in your console, can you check the `baseServiceIO.ts` file. It should have the following `await` and `return` statements highlighted in red which I added in version `1.3.20`.
<img width="975" alt="Screenshot 2023-10-26 at 16 41 44" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/5fc8a170-88c9-402b-83fa-926cb107cf62">

**Comment by guinanlin** [comment] 2023-10-26 16:21
> If the exact same code from the sandbox doesn't work in your local application then I would assume your app is running the `1.3.19` version instead. Can you try to delete the `package-lock.json` file and `node_modules` folder, and do `npm install` again to see if it fixes it.

try back 1.3.19.  still the same error.

```
deep-chat.js?v=e9fc36ea:1628 
        
        
       POST https://api.openai.com/v1/chat/completions 400 (Bad Request)
_callee11$ @ deep-chat.js?v=e9fc36ea:1628
tryCatch @ deep-chat.js?v=e9fc36ea:209
（匿名） @ deep-chat.js?v=e9fc36ea:292
（匿名） @ deep-chat.js?v=e9fc36ea:232
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:452
_next @ deep-chat.js?v=e9fc36ea:470
Promise.then（异步）
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:461
_next @ deep-chat.js?v=e9fc36ea:470
（匿名） @ deep-chat.js?v=e9fc36ea:475
（匿名） @ deep-chat.js?v=e9fc36ea:467
request @ deep-chat.js?v=e9fc36ea:1696
_callee16$ @ deep-chat.js?v=e9fc36ea:4057
tryCatch @ deep-chat.js?v=e9fc36ea:209
（匿名） @ deep-chat.js?v=e9fc36ea:292
（匿名） @ deep-chat.js?v=e9fc36ea:232
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:452
_next @ deep-chat.js?v=e9fc36ea:470
（匿名） @ deep-chat.js?v=e9fc36ea:475
（匿名） @ deep-chat.js?v=e9fc36ea:467
request @ deep-chat.js?v=e9fc36ea:4065
_callee17$ @ deep-chat.js?v=e9fc36ea:4083
tryCatch @ deep-chat.js?v=e9fc36ea:209
（匿名） @ deep-chat.js?v=e9fc36ea:292
（匿名） @ deep-chat.js?v=e9fc36ea:232
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:452
_next @ deep-chat.js?v=e9fc36ea:470
（匿名） @ deep-chat.js?v=e9fc36ea:475
（匿名） @ deep-chat.js?v=e9fc36ea:467
callServiceAPI @ deep-chat.js?v=e9fc36ea:4091
_callee19$ @ deep-chat.js?v=e9fc36ea:4140
tryCatch @ deep-chat.js?v=e9fc36ea:209
（匿名） @ deep-chat.js?v=e9fc36ea:292
（匿名） @ deep-chat.js?v=e9fc36ea:232
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:452
_next @ deep-chat.js?v=e9fc36ea:470
（匿名） @ deep-chat.js?v=e9fc36ea:475
（匿名） @ deep-chat.js?v=e9fc36ea:467
callAPI @ deep-chat.js?v=e9fc36ea:4148
_callee74$ @ deep-chat.js?v=e9fc36ea:10811
tryCatch @ deep-chat.js?v=e9fc36ea:209
（匿名） @ deep-chat.js?v=e9fc36ea:292
（匿名） @ deep-chat.js?v=e9fc36ea:232
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:452
_next @ deep-chat.js?v=e9fc36ea:470
Promise.then（异步）
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:461
_next @ deep-chat.js?v=e9fc36ea:470
Promise.then（异步）
asyncGeneratorStep @ deep-chat.js?v=e9fc36ea:461
_next @ deep-chat.js?v=e9fc36ea:470
（匿名） @ deep-chat.js?v=e9fc36ea:475
（匿名） @ deep-chat.js?v=e9fc36ea:467
submit @ deep-chat.js?v=e9fc36ea:10821
submitFromInput @ deep-chat.js?v=e9fc36ea:10745
onKeydown @ deep-chat.js?v=e9fc36ea:805
deep-chat.js?v=e9fc36ea:937 TypeError: Cannot read properties of undefined (reading '0')
    at DeepChat2.responseInterceptor (A10.vue:78:40)
    at _callee10$ (deep-chat.js?v=e9fc36ea:1650:102)
    at tryCatch (deep-chat.js?v=e9fc36ea:209:40)
    at Generator.<anonymous> (deep-chat.js?v=e9fc36ea:292:18)
    at Generator.next (deep-chat.js?v=e9fc36ea:232:21)
    at asyncGeneratorStep (deep-chat.js?v=e9fc36ea:452:24)
    at _next (deep-chat.js?v=e9fc36ea:470:9)
    at deep-chat.js?v=e9fc36ea:475:7
    at new Promise (<anonymous>)
    at deep-chat.js?v=e9fc36ea:467:12
```


otherwise, because I didn't run on the source, so I cannot  check the baseServiceIO.ts (on await and return.)

But this thing is really weird. I tried to adjust the sandbox package and vue version to be the same as mine. The sandbox runs very well. But in my environment, it cannot run. Here is the package of my environment. Also send the conf.

```
{
    "name": "t-vue",
    "version": "3.7.0",
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview",
        "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
    },
    "dependencies": {
        "axios": "^1.4.0",
        "chart.js": "3.3.2",
        "deep-chat": "1.3.19",
        "exceljs": "4.3.0",
        "file-saver": "2.0.5",
        "frappe-js-sdk": "^1.2.4",
        "ip": "^1.1.8",
        "luckyexcel": "1.0.1",
        "primeflex": "^3.2.1",
        "primeicons": "^6.0.1",
        "primevue": "3.28.0",
        "vee-validate": "4.9.6",
        "vue": "^3.2.41",
        "vue-router": "^4.1.5",
        "vxe-table": "^4.4.2",
        "xe-utils": "^3.5.11",
        "yup": "^1.3.2"
    },
    "devDependencies": {
        "@rushstack/eslint-patch": "^1.1.4",
        "@vitejs/plugin-vue": "^4.1.0",
        "@vue/eslint-config-prettier": "^7.0.0",
        "eslint": "^8.22.0",
        "eslint-plugin-vue": "^9.3.0",
        "prettier": "^2.7.1",
        "sass": "^1.55.0",
        "vite": "^4.2.1"
    },
    "main": "index.js",
    "repository": "https://xxxxxx.git",
    "author": "xxxxx",
    "license": "MIT"
}

```

and then I  try my API to run on the sandbox, it also run well. so , it relate to my envoirment.

 It should be caused by some packages interacting with each other.

**Comment by OvidijusParsiunas** [comment] 2023-10-26 16:30
It is very likely that this is caused by something else in your environment. I have updated the latest version to `1.3.21` as `1.3.20` had a few console logs that I forgot to remove.

Can you use `1.3.21`, run `npm install` and in the `package-lock.json` file do you have the following?

```
    "node_modules/deep-chat": {
      "version": "1.3.21",
      "resolved": "https://registry.npmjs.org/deep-chat/-/deep-chat-1.3.21.tgz",
      "integrity": "sha512-WEWCLj0g1MAnkSLbFJniILragjRjXppJ5zqNTb6A9vCC87v5ySXM9R4X1POiDZ6Q13uQuhwOwBpOUgUENcNt2w==",
      "dependencies": {
        "@microsoft/fetch-event-source": "^2.0.1",
        "remarkable": "^2.0.1",
        "speech-to-element": "^0.1.66"
      }
    },
```

and 

```
    "deep-chat": {
      "version": "1.3.21",
      "resolved": "https://registry.npmjs.org/deep-chat/-/deep-chat-1.3.21.tgz",
      "integrity": "sha512-WEWCLj0g1MAnkSLbFJniILragjRjXppJ5zqNTb6A9vCC87v5ySXM9R4X1POiDZ6Q13uQuhwOwBpOUgUENcNt2w==",
      "requires": {
        "@microsoft/fetch-event-source": "^2.0.1",
        "remarkable": "^2.0.1",
        "speech-to-element": "^0.1.66"
      }
    },
```

**Comment by guinanlin** [comment] 2023-10-26 16:55
yeah,  1.3.21 works well 

Thank you very much for your help, I really appreciate it, it’s night in China, I wish you sweet dreams:-)

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/44794953/8e7d14e0-0cec-4f60-8b32-1c84d8eb57c9)

**Comment by guinanlin** [comment] 2023-10-26 16:58
summary up the vue3 request call and share to others.
outer api call:

```
<deep-chat
    id="chat-element"
    style=" border-radius: 10px;
            height: calc(95vh - 5.5rem);;
            width: 600px;
            border: 1px solid rgb(202, 202, 202);
            font-family: Inter, sans-serif, Avenir, Helvetica, Arial;
            font-size: 1.2rem;
            background-color: white;
            position: relative;"

    :request="{
        url: 'https://xxxxxtions',
        method: 'POST',
        headers: {
            Authorization: 'Bearer LxxxxxuzD0tO7'
        }      
    }"   

    :requestInterceptor="(request) => {
        // request.body = {prompt: request.body.messages[0].text};
        request.body = { app_code: 'pKxxx5',
                         messages: [
                            {
                            role: 'user',
                            content: request.body.messages[0].text
                            },
                        ]
                        };
        return request;      
    }"

    :responseInterceptor="(response) => {
            // const responseText = // extract it from the response argument
            return { text: response.choices[0].message.content };
    }"  
/>
```



OpenAI api call:

```
<template>
  <deep-chat
    :request="{
      url: 'https://api.openai.com/v1/chat/completions',
      headers: {
        Authorization: 'Bearer sxxxxTgOssZ7w7',
      },
    }"
    :requestInterceptor="
      (request) => {
        request.body = {
          messages: [{ role: 'user', content: request.body.messages[0].text }],
          model: 'gpt-3.5-turbo',
        };
        return request;
      }
    "
    :responseInterceptor="
      (response) => {
        return { text: response.choices[0].message.content };
      }
    "
  />
</template>

<script>
import "deep-chat";
</script>

```

**Comment by OvidijusParsiunas** [comment] 2023-10-26 17:04
Good to hear @guinanlin!

I will close this issue, but if you have any other problems or questions, you can feel free to raise a new one!

晚安

**Closed by OvidijusParsiunas** 2023-10-26 17:04 UTC
Labels: bug, advice
