### ISSUE TITLE
Feature request: Customizable OpenAI endpoint

### ISSUE THREAD

**Issue by nstogner** [OvidijusParsiunas/deep-chat#288] opened 2024-10-26 21:27 UTC
**Background**

Hi, I am one of the authors of [KubeAI](https://github.com/substratusai/kubeai) and I am starting to write a guide on how to integrate with Deep Chat because it looks like a great way to implement a lightweight chat UI!

**Feature Request**

KubeAI provides an OpenAI-compatible endpoint so it would be nice to be able to plug-n-play with the existing OpenAI "direct connection" feature in Deep Chat. This would require customizing the OpenAI endpoint to send requests to an address other than `api.openai.com` (note: this is how we integrate with projects like https://docs.openwebui.com/ today).

This feature would open the door for direct integration with a lot of popular OSS projects like the popular [vLLM](https://github.com/vllm-project/vllm) engine (which also provides an OpenAI-compatible endpoint).

**What I have tried:**

I tried this approach but DeepChat still sent requests to OpenAI:
https://github.com/OvidijusParsiunas/deep-chat/issues/144#issuecomment-2000052344

<img width="547" alt="Screenshot 2024-10-26 at 5 19 42 PM" src="https://github.com/user-attachments/assets/b8f82556-46ed-472c-b196-d549de868446">

```html
    <deep-chat id="chat-element" style="background-color: #f7f7f7; border-radius: 8px"
        request='{"url":"http://localhost:8000/openai/v1/chat/completions"}'
        directConnection='{"openAI":{"chat":true,"key": "placeholder", "validateKeyProperty": false}}'
        textInput='{"placeholder":{"text": "Welcome to the demo!"}}'></deep-chat>
```

**Comment by OvidijusParsiunas** [comment] 2024-10-27 11:33
Hi @nstogner.

First of all, very cool project! I gave it a star ⭐ 

The error you are seeing above is likely caused by the header that the OpenAI API key is applied to. The server that you are trying to call might require a different header name or a different way of adding the key.

Based on what you have done so far, you can go in two directions:

1. You can either utilise the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) to change the headers of the outgoing requests, or even the request body to whatever your server expects.
2. You can use the [handler](https://deepchat.dev/docs/connect#Handler) function to fully control the request logic. This is most appropriate for connecting to any custom service.

Let me know if you have any issues in using either of these. Thanks!

**Comment by OvidijusParsiunas** [comment] 2024-10-27 11:33
Another quick small tip. The `request` property has now been renamed to `connect` in the latest versions of Deep Chat. :)

**Comment by OvidijusParsiunas** [comment] 2024-10-30 10:01
If you want to attach your own headers to the outgoing requests, the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) should allow you to achieve this.

Having said this, one of the reasons why you are experiencing issues is because you are using the [directConnection openAI](https://deepchat.dev/docs/directConnection/OpenAI#openAI) configuration which tailors the outgoing requests to be for the actual OpenAI services. If you are experiencing any more difficulties I would advise you to fully use the [`connect`](https://deepchat.dev/docs/connect) property instead. You can take full advantage of the [handler](https://deepchat.dev/docs/connect#Handler) function or combine it with the [interceptors](https://deepchat.dev/docs/interceptors) to get the desired outcome. Here is a full [video](https://www.youtube.com/watch?v=NuRhPeqDCus&t=1s) on how to connect to any service using the interceptors and another [video](https://www.youtube.com/watch?v=orRVFA5AWfU) to connect via the handler.

Let me know if you have any other questions. Thanks!

**Comment by nstogner** [comment] 2024-10-31 02:18
The request interceptor worked!

PS:: I also ended up using the interceptor to set the model in the request. In my example, the model is selected from a separate dropdown menu. I tried updating the `<deep-chat>` element's `directionConnection` attribute, but it does not appear to react to this change.

**Comment by nstogner** [comment] 2024-10-31 02:21
Thank you very much for all of the help! We will be publishing the guide soon and will include a link to deep chat.

**Comment by OvidijusParsiunas** [comment] 2024-10-31 11:39
Good to hear that it worked! I will be closing the issue, thanks!

**Closed by OvidijusParsiunas** 2024-10-31 11:39 UTC
Labels: advice
